# Server 配置
server:
  port: 9090
  servlet:
    context-path: /swiftstock
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: false

# Spring 配置
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,resources/**,templates/**
    livereload:
      enabled: true
      port: 35729
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_warehouse?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,file:./frontend/dist/
      add-mappings: true
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-c7f04122bc9946cf9f53c008bacd1568  # 填你自己的
      chat:
        options:
          model: deepseek-chat  # 或 deepseek-reasoner（推理模型）
          temperature: 0.3
          max-tokens: 300

# Servlet 配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.swiftstock.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.swiftstock: debug
    org.springframework.security: debug
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  file:
    name: logs/swiftstock.log

# JWT 配置
jwt:
  secret: ${JWT_SECRET:ChangeThisSecretKey}
  expiration-millis: 86400000

# API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
  show-actuator: false
  packages-to-scan: com.swiftstock.controller
  #http://localhost:8088/swiftstock/login